"""Добавил поле image_filenames в Bike

Revision ID: fd0eb1f07660
Revises: 1e7986756b67
Create Date: 2025-06-20 04:26:33.291376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0eb1f07660'
down_revision = '1e7986756b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filenames', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.drop_column('image_filenames')

    # ### end Alembic commands ###
